services:
  eureka-server:
    build: eureka-server
    container_name: eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 8761:8761
    networks:
      - spring-app

  config-server:
    build: config-server
    container_name: config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 8888:8888
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - spring-app

  math-service:
    build: math-service
    container_name: math-service
    restart: always
    ports:
      - 8080:8080
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - spring-app

  # Replica
  math-service-1:
    build: math-service
    container_name: math-service-1
    restart: always
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - spring-app

  history-service:
    build: history-service
    container_name: history-service
    restart: always
    ports:
      - 8081:8081
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - spring-app

  examinator-service:
    build: examinator-service
    container_name: examinator-service
    restart: always
    ports:
      - 8082:8082
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - spring-app

networks:
  spring-app:
    driver: bridge