server:
  port: 8081

spring:
  application:
    name: examinator-service
  cloud:
    config:
      discovery:
        enabled: false
        service-id: config-server
      enabled: false

management:
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true

eureka:
  client:
    enabled: false

services:
  exams: math, history