server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        health:
          down-health-status:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka